name: Publish
on:
  workflow_run:
    workflows:
      - Build
      - Build Documentation
    branches:
      - main
      - iceflower/rolling-fox
    types:
      - completed

env:
  DEBIAN_FRONTEND: "noninteractive"
  preview_git_path: './preview/'
  main_git_path: './main/'

jobs:
  publish-devel-build:
    name: Publish Development Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/download-artifact@v3
        with:
          name: build_linux_clang.tar.xz
          path: path/to/artifact

      - uses: actions/download-artifact@v3
        with:
          name: build_linux_gcc.tar.xz
          path: path/to/artifact

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: path/to/artifact
